BUCKET_NAME: "fraud-finder-lab-fraudfinder"
PROJECT: "fraud-finder-lab"
REGION: "us-central1"
ID: "8wc8m"
FEATURESTORE_ID: "fraudfinder_8wc8m"
MODEL_NAME: "ff_model"
ENDPOINT_NAME: "ff_model_endpoint"
TRAINING_DS_SIZE: !!str "1000"
DATA_DIR: "data"
TRAIN_DATA_DIR: "train"
CUSTOMER_ENTITY: "customer"
TERMINAL_ENTITY: "terminal"
TARGET: "tx_fraud"

## Custom Training
MODEL_SERVING_IMAGE_URI: "us-docker.pkg.dev/vertex-ai/prediction/xgboost-cpu.1-7:latest"
IMAGE_NAME: "dask-xgb-classificator"
TRAIN_COMPUTE: "n1-standard-4"
DEPLOY_COMPUTE: "n1-standard-4"
